<?php

/**
 * @file
 * Contains doctor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function doctor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the doctor module.
    case 'help.page.doctor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Doctor Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function doctor_theme($existing, $type, $theme, $path) {
    return [
        'doctor' => [                            // the entity id// template directory in module or theme
            'template'  => 'doctor',                // defines base template as /artwork.html.twig
            'render element' => 'elements',          // Theme API call to define the container of the entity in the render array
            // The entity will be prefixed with a hash sign as ['elements']['#artwork']
        ],
        'doctor_list' => [
            'variables' => ['doctors' => NULL, 'name'=> NULL],
            'path' => $path . '/templates/',
            'template' => 'doctor-list'
        ],
        'doctor_banner_block' => [
            'variables' => ['doctor' => NULL],
            'path' => $path . '/templates/',
            'template' => 'doctor-banner'
        ],
    ];
}


