<?php

/**
 * @file
 * Contains doctor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function doctor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the doctor module.
    case 'help.page.doctor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Doctor Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function doctor_theme($existing, $type, $theme, $path) {
    return [
        'doctor' => [                            // the entity id// template directory in module or theme
            'template'  => 'doctor',                // defines base template as /artwork.html.twig
            'render element' => 'elements',          // Theme API call to define the container of the entity in the render array
            // The entity will be prefixed with a hash sign as ['elements']['#artwork']
        ],
        'doctor_list' => [
            'variables' => ['doctors' => NULL, 'name'=> NULL],
            'path' => $path . '/templates/',
            'template' => 'doctor-list'
        ],
        'doctor_banner_block' => [
            'variables' => ['doctor' => NULL],
            'path' => $path . '/templates/',
            'template' => 'doctor-banner'
        ],
    ];
}

function getStoreByDoctor($id){
    $ids = \Drupal::entityQuery('store_locator')
        ->condition('field_doctor',$id)
        ->execute();
    $result = \Drupal\store_locator\Entity\StoreLocator::loadMultiple($ids);
    if($result){
        $store = reset($result);
        return $store;
    }else{
        return false;
    }
}

/**
 * Implements hook_form_alter().
 */
function doctor_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change form id here.
  if ($form_id == 'doctor_add_form') {
    $form['#attached']['library'][] = 'doctor/admin-style';
  }
  if($form_id=='doctor_edit_form'){
    $form['#attached']['library'][] = 'doctor/admin-style-edit';
  }
  if($form['#form_id']=='views_exposed_form' && $form['#id']=='views-exposed-form-clinic-page-1'){
    $form['date_select'] = ['#type' =>'select','#options' => [''=>'--Select Date--','cny'=>'CNY Holiday','easter' => 'Easter Holiday','chris'=>'Christmas Holiday']];

    $form['search_api_fulltext']['#prefix'] = '<div class="form_clinic_address"><a href="#clinic_address"
data-toggle="collapse">Clinic / Address - 地址</a><div
id="clinic_address" class="collapse">';
    $form['search_api_fulltext']['#suffix'] = '</div></div>';
    $form['search_api_fulltext']['#weight'] = 1;
    $form['field_clinic_distric']['#weight'] = 2;
    $form['field_clinic_distric']['#type'] = 'checkboxes';
    $form['field_clinic_distric']['#prefix'] = '<div class="field_clinic_distric"><a href="#clinic_distric"
data-toggle="collapse">Select District - 地區</a><div
id="clinic_distric" class="collapse">';
    $form['field_clinic_distric']['#suffix'] = '</div></div>';
    $form['date_select']['#weight'] = 3;
    $form['field_cny_confirm']['#weight'] = 4;
    $form['field_cny_confirm']['#states'] = [
      'visible' => [
        ':input[name="date_select"]' => ['value' => 'cny'],
      ],
    ];
    $form['field_easter_day_confirm']['#states'] = [
      'visible' => [
        ':input[name="date_select"]' => ['value' => 'easter'],
      ],
    ];
    $form['field_christmas_day_confirm']['#states'] = [
      'visible' => [
        ':input[name="date_select"]' => ['value' => 'chris'],
      ],
    ];
    $form['field_easter_day_confirm']['#weight'] = 5;
    $form['field_christmas_day_confirm']['#weight'] = 6;
    $form['field_speciality']['#weight'] = 7;
    $form['date_select']['#prefix'] = '<div class="field_cny_confirm"><a href="#cny_date"
data-toggle="collapse">Select Date(s) - 日期</a><div
id="cny_date" class="collapse">';
    $form['field_cny_confirm']['#type'] = 'checkboxes';
    $form['field_easter_day_confirm']['#type'] = 'checkboxes';
    $form['field_christmas_day_confirm']['#type'] = 'checkboxes';
    $form['field_christmas_day_confirm']['#suffix'] = '</div></div>';

    $form['field_speciality']['#prefix'] = '<div class="form_clinic_address"><a href="#speciality"
data-toggle="collapse">Specialty - 地址</a><div
id="speciality" class="collapse">';
    $form['field_speciality']['#suffix'] = '</div></div>';

  }
  if($form['#form_id']=='views_exposed_form' && $form['#id']=='views-exposed-form-media-library-widget'){
    $user = \Drupal::currentUser();
    if(in_array('doctor',$user->getRoles()) || in_array('hkdu_members', $user->getRoles()) || in_array('council_members', $user->getRoles())){
//     $form['directory']['#options'] = [159=>'Clinic - Name Card'];
    }
  }

}


