<?php

/**
 * @file
 * Contains doctor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function doctor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the doctor module.
    case 'help.page.doctor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Doctor Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function doctor_theme($existing, $type, $theme, $path) {
    return [
        'doctor' => [                            // the entity id// template directory in module or theme
            'template'  => 'doctor',                // defines base template as /artwork.html.twig
            'render element' => 'elements',          // Theme API call to define the container of the entity in the render array
            // The entity will be prefixed with a hash sign as ['elements']['#artwork']
        ],
        'doctor_list' => [
            'variables' => ['doctors' => NULL, 'name'=> NULL],
            'path' => $path . '/templates/',
            'template' => 'doctor-list'
        ],
        'doctor_banner_block' => [
            'variables' => ['doctor' => NULL],
            'path' => $path . '/templates/',
            'template' => 'doctor-banner'
        ],
    ];
}

function getStoreByDoctor($id){
    $ids = \Drupal::entityQuery('store_locator')
        ->condition('field_doctor',$id)
        ->execute();
    $result = \Drupal\store_locator\Entity\StoreLocator::loadMultiple($ids);
    if($result){
        $store = reset($result);
        return $store;
    }else{
        return false;
    }
}

/**
 * Implements hook_form_alter().
 */
function doctor_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change form id here.
  if ($form_id == 'doctor_add_form') {
    $form['#attached']['library'][] = 'doctor/admin-style';
  }
  if($form_id=='doctor_edit_form'){
    $form['#attached']['library'][] = 'doctor/admin-style-edit';
  }
  if($form['#form_id']=='views_exposed_form' && $form['#id']=='views-exposed-form-clinic-page-1'){

    $form['search_api_fulltext']['#prefix'] = '<div class="form_clinic_address"><a href="#clinic_address" 
data-toggle="collapse">Clinic
/Address</a><div 
id="clinic_address" class="collapse">';
    $form['search_api_fulltext']['#suffix'] = '</div></div>';
    $form['field_clinic_distric']['#type'] = 'checkboxes';
    $form['field_clinic_distric']['#prefix'] = '<div class="field_clinic_distric"><a href="#clinic_distric" 
data-toggle="collapse">Select District</a><div 
id="clinic_distric" class="collapse">';
    $form['field_clinic_distric']['#suffix'] = '</div></div>';

    $form['field_cny_confirm']['#prefix'] = '<div class="field_cny_confirm"><a href="#cny_date" 
data-toggle="collapse">Select Date(s)</a><div 
id="cny_date" class="collapse">';
    $form['field_cny_confirm']['#suffix'] = '</div></div>';
    $form['field_cny_confirm']['#type'] = 'checkboxes';

  }

}

