<?php

/**
 * @file
 * Contains clinical_focus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function clinical_focus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the clinical_focus module.
    case 'help.page.clinical_focus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Clinical Focus Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function clinical_focus_theme($existing, $type, $theme, $path) {
    return [
        'clinical_focus' => [                            // the entity id// template directory in module or theme
            'template'  => 'clinical_focus',                // defines base template as /artwork.html.twig
            'render element' => 'elements',          // Theme API call to define the container of the entity in the render array
            // The entity will be prefixed with a hash sign as ['elements']['#artwork']
        ],
        'clinical_focus_list' => [
            'variables' => ['clinical_focus' => NULL, 'author'=>NULL, 'date' =>NULL, 'tags' => NULL,'get' => NULL,'search'=>NULL],
            'path' => $path . '/templates/',
            'template' => 'clinical-focus-list'
        ],
        'clinical_focus_home' => [
            'variables' => ['clinical_focus' => NULL, 'author'=>NULL, 'date' =>NULL],
            'path' => $path . '/templates/',
            'template' => 'clinical-focus-home'
        ],
        'clinical_focus_banner_block' => [
            'variables' => ['clinical_focus' => NULL],
            'path' => $path . '/templates/',
            'template' => 'clinical-focus-banner'
        ],
    ];
}

