<?php

/**
 * @file
 * Contains event_cart.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_cart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_cart module.
    case 'help.page.event_cart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event AddTo Cart') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function event_cart_theme() {
  return [
    'event_cart' => [
      'render element' => 'children',
    ],
  ];
}
