<?php

/**
 * @file
 * Contains store_locator.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\store_locator\Helper\GoogleApiKeyHelper;
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function store_locator_theme($existing, $type, $theme, $path)
{

    return [
        'location_data' => [
            'variables' => ['location_search' => NULL],
            'file' => 'store_locator.theme.inc',
        ],
    ];

}

/**
 * Implements hook_entity_view_alter().
 */
function store_locator_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display)
{
    if ($entity->getEntityTypeId() == 'store_locator' && $build['#view_mode'] == 'full' && !empty($build['name']['#object'])) {
        $fid = \Drupal::config('store_locator.settings')->get('marker');
        $icon_url = '';
        if (!is_null($fid)) {
            $file_entity = File::load($fid);
            $icon_url = file_create_url($file_entity->getFileUri());
        }
        $lat = $build['name']['#object']->get('latitude')->value;
        $lng = $build['name']['#object']->get('longitude')->value;
        $lat_lng = ['lat' => (float)$lat, 'lng' => (float)$lng];
        $build['#attached']['drupalSettings']['store_locator']['latlng'] = $lat_lng;
        $build['#attached']['drupalSettings']['store_locator']['icon'] = $icon_url;
        $build['map']['#markup'] = '<div id="map" class="loc-map store-locator-page-view"></div>';
        $build['map']['#weight'] = 100;
        $build['#attached']['library'][] = 'store_locator/store_locator.page';
        $googleMapKey = GoogleApiKeyHelper::getGoogleApiKey();
        $build['#attached']['html_head'][] = [$googleMapKey, 'googleMapKey'];
    }
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function store_locator_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if ($form_id == 'store_locator_add_form' || $form_id=='store_locator_edit_form') {
        if (isset($_GET['doctor_id'])) {
            $doctor = \Drupal\doctor\Entity\DoctorEntity::load($_GET['doctor_id']);
            $form['name']['widget'][0]['value']['#default_value'] = $doctor->getName();
            $form['field_doctor']['widget'][0]['target_id']['#default_value'] = $doctor;
            $form['field_doctor']['#attributes']['class'][] = 'hidden';
        }

    }

}
