<?php

/**
 * @file
 * Contains healthy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function healthy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the healthy module.
    case 'help.page.healthy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Healthy Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function healthy_theme($existing, $type, $theme, $path) {
  return [
      'healthy' => [                            // the entity id// template directory in module or theme
          'template'  => 'healthy',                // defines base template as /artwork.html.twig
          'render element' => 'elements',          // Theme API call to define the container of the entity in the render array
          // The entity will be prefixed with a hash sign as ['elements']['#artwork']
      ],
      'healthy_list' => [
          'variables' => ['healthies' => NULL, 'author'=>NULL, 'date' =>NULL, 'tags' => NULL,'get' => NULL,'search'=>NULL],
          'path' => $path . '/templates/',
          'template' => 'healthy-list'
      ],
      'healthy_home' => [
          'variables' => ['healthies' => NULL, 'author'=>NULL, 'date' =>NULL],
          'path' => $path . '/templates/',
          'template' => 'healthy-home'
      ],
      'healthy_banner_block' => [
          'variables' => ['healthy' => NULL],
          'path' => $path . '/templates/',
          'template' => 'healthy-banner'
      ],
  ];
}
