<?php

/**
 * @file
 * Contains cme_user.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function cme_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cme_user module.
    case 'help.page.cme_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Customer relation for users') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cme_user_theme($existing, $type, $theme, $path) {
  return [
    'cme_user' => [
      'render element' => 'children',
    ],
    'cme_user_code' => [
      'variables' => ['user' => NULL, 'qrcode' => NULL],
      'path' => $path . '/templates/',
      'template' => 'qrcode',
    ],
    'admin_user_report' => [
      'variables' => ['data' => NULL],
      'path' => $path . '/templates/',
      'template' => 'admin-user-report',
    ],
    'user_report' => [
      'variables' => ['user' => NULL, 'scores' => NULL, 'total' => NULL, 'total_study' => NULL, 'total_lecture' => NULL, 'from'=>NULL, 'to' => NULL,'now'=>NULL, 'is_cycle'=> NULL],
      'path' => $path . '/templates/',
      'template' => 'report',
    ],
  ];
}

function cme_user_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  if ($form_id == 'user_register_form') {
    $form['field_membership_type']['widget']['#options']['_none'] = 'Select a membership Type';
    unset($form['field_membership_type']['widget']['#options']['anonymous']);
    unset($form['field_membership_type']['widget']['#options']['authenticated']);
    unset($form['field_membership_type']['widget']['#options']['cme_member']);
    unset($form['field_membership_type']['widget']['#options']['council_members']);
    unset($form['field_membership_type']['widget']['#options']['admins']);
    unset($form['field_membership_type']['widget']['#options']['doctor']);
    unset($form['field_membership_type']['widget']['#options']['drug_suppliers']);
    $form['field_membership_type']['widget']['#options']['administrator'] = 'Non-Member:HKDU as CME Administrator';
    $form['field_membership_type']['widget']['#options']['tester'] = 'Tester(Office use only)';
    $form['field_membership_type']['widget']['#options']['invited'] = 'Non-Member:Invited';
    $form['actions']['submit']['#suffix'] = '<div class="login-link"><a href="/user/login">Login</a></div>';
    //  $form['#validate'][] = 'cme_user_validation_membership';
  }
  if ($form_id == 'user_login_form') {
    $form['actions']['submit']['#suffix'] = '<div class="register-link"><a href="/user/register">Request an account</a><a class="password-link" href="/user/password">Reset password?</a></div>';
  }
  if ($form_id == 'user_pass') {
    $form['actions']['submit']['#suffix'] = '<div class="login-link"><a href="/user/login">Login</a></div>';
  }
  if ($form_id == 'user_form') {
    //   dpm($form);
    //  $form['user_picture']['#description']
    unset($form['field_policy']);
    unset($form['field_guide_info']);
  }
}

function cme_user_menu_local_tasks_alter(&$data, $route_name) {

  //do nothing if this ain't a display page

  if ($route_name == 'entity.user.canonical') {
    $current_path = \Drupal::service('path.current')->getPath();
    $path = explode('/', $current_path);
    $id = $path[2];

    $data['tabs'][0]['cme_user.user_qrcode_controller_qrcode.qrcode'] = [
      '#theme' => 'menu_local_task',
      '#weight' => -10,
      '#link' => [
        'title' => t('QR Code'),
        //create a url object. here from a route, but can be Url object.
        'url' => Url::fromRoute('cme_user.user_qrcode_controller_qrcode', [
          //set route parameters. check modulename.routing.yml for parameters
          'uid' => $id,
        ]),
      ],
    ];
  }

  //try to get the currently displayed node
}

/**
 * Implements hook_entity_presave().
 */
function cme_user_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() == 'user') {
    $entity->addRole($entity->get('field_membership_type')->target_id);
  }
}

/**
 * @param $user
 *
 * @return false|int|string
 */
function getCycle($user){
  $year = date('Y',strtotime($user->get('field_cme_join_date')->value));

  $current = getYear($year);
  $first = date();
  if($current == 0){
    return false;
  }
  if($current == 1){
    $first = date('Y') - 1;
  }
  if($current == 2){
    $first = date('Y') - 2;
  }
  if($current == 3){
    $first = date('Y') - 3;
  }
  return $first;
}

/**
 * @param $year
 *
 * @return int
 */
function getYear($year){
  $now = date('Y');
  $current = $now - $year;
  if($current == 0){
    return 3;
  }
  if($current == 2){
    return 2;
  }
  if($current == 1){
    return 1;
  }
  if($current < 0){
   return 0;
  }
  if($current > 3){
   return calCycle($current);
  }
}

function calCycle($year){
  if($year <= 3){
    return $year;
  }else{
    $now = $year -3;
  }
  return calCycle($now);
}

