<?php

/**
 * @file
 * Contains notify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function notify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the notify module.
    case 'help.page.notify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Notification for HKDU') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function notify_theme($existing, $type, $theme, $path) {
  return [
    'notify' => [
      'render element' => 'children',
    ],
    'notify_alert' => [
      'variables' => [
        'count' => NULL,
      ],
    ],
    'notify_list' => [
      'variables' => [
        'notifies' => NULL,
      ],
    ],
  ];
}

